pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                println(new Date().getTime())
                echo 'Hello World ...WebServer '
                println(new Date().getTime())
            }
        }
    }
}
