pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                echo 'Hello World ...WebServer'
                println(Date.getTime())
            }
        }
    }
}
