pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                echo "TimeStamp: ${Util.getTimeSpanString(System.currentTimeMillis()}"
                echo 'Hello World ...WebServer'
                echo "TimeStamp: ${Util.getTimeSpanString(System.currentTimeMillis()}"
            }
        }
    }
}
