pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                println(new Date().getTime())
                dir('webServer') {
                    sh "npm set registry http://localhost:4872/"
                    sh "npm install"
                    sh "npm run build:test"
                }
                println(new Date().getTime())
            }
        }

        stage('deploy') {
            steps {
                println(new Date().getTime())
                sh "npm run test:devTest"
                println(new Date().getTime())
            }
        }
    }
}
