pipeline {
    agent{
        node {
            label 'my-defined-label'
        }
    }
    stages {
        stage('prepare') {
            steps {
                println(new Date().getTime())
                httpRequest contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody:  """{"serviceName":"test:test.prepare","start":${new Date().getTime()}}""", url: "http://localhost:8022/"
                dir('webServer') {
                    sh "npm set registry http://localhost:4872/"
                    sh "npm install"
                }
                httpRequest contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody: """{"serviceName":"test:test.prepare","end":${new Date().getTime()}}""", url: "http://localhost:8022/"
                println(new Date().getTime())
            }
        }
        stage('build') {
            steps {
                println(new Date().getTime())
                httpRequest contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody:  """{"serviceName":"test:test.build","start":${new Date().getTime()}}""", url: "http://localhost:8022/"
                dir('webServer') {
                    sh "npm set registry http://localhost:4872/"
                    sh "npm install"
                    sh "npm run build:test"
                }
                httpRequest contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody: """{"serviceName":"test:test.build","end":${new Date().getTime()}}""", url: "http://localhost:8022/"
                println(new Date().getTime())
            }
        }

        stage('serviceTest') {
            steps {
                println(new Date().getTime())
                httpRequest contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody:  """{"serviceName":"test:test.serviceTest","start":${new Date().getTime()}}""", url: "http://localhost:8022/"
                dir('webServer') {
                    sh "npm run test:test"
                }
                httpRequest contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody: """{"serviceName":"test:test.serviceTest","end":${new Date().getTime()}}""", url: "http://localhost:8022/"
                println(new Date().getTime())
            }
        }
    }
}
