pipeline {
    agent any
    stages {
        stage('prepare') {
            steps {
                println(new Date().getTime())
                httpRequest contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody:  """{"serviceName":"testTT","start":${new Date().getTime()}}""", url: "http://localhost:8022/"
                dir('webServer') {
                    sh "npm set registry http://localhost:4872/"
                    sh "npm install"
                }
                httpRequest contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody: """{"serviceName":"testTT","end":${new Date().getTime()}}""", url: "http://localhost:8022/"
                println(new Date().getTime())
            }
        }
        stage('build') {
            steps {
                println(new Date().getTime())
                dir('webServer') {
                    sh "npm set registry http://localhost:4872/"
                    sh "npm install"
                    sh "npm run build:test"
                }
                println(new Date().getTime())
            }
        }

        stage('serviceTest') {
            steps {
                println(new Date().getTime())
                dir('webServer') {
                    sh "npm run test:test"
                }
                println(new Date().getTime())
            }
        }
    }
}
